### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by vivekebics** [wso2/product-emm#234]
How to improve the page loading speed ?

**Comment by Flashtony76** [comment]
We have the same issue. 100 % CPU load on 8Core Intel i7 with 24GB of Ram. Loading page with 3 devices takes 4 seconds.

**Comment by Kamidu** [comment]
@ghost and @Flashtony76 Above performance issues being fixed in EMM 2.2.0-Beta. Fixes can be found on the master branch.
