### ISSUE TITLE
Help me setting up Project source code

### ISSUE THREAD

**Issue by tuanlethanh** [wso2/product-emm#322]
Hello friends,

I don't know how to setting up project source code after i download from github page. Because, i am working in .net and i do not knowledge for JAVA config. Please help me config project step by step. I am using Netbean. Please give me any advice to use eclipse or NetBean?

**Comment by ayyoob** [comment]
It is a maven based project therefore you can directly import it into eclipse or Netbeans. You can follow the guide [1] & [2] on how to import it in eclipse and netbeans respectively.

[1] http://javapapers.com/java/import-maven-project-into-eclipse/
[2] http://wiki.netbeans.org/MavenBestPractices#Open_existing_project

**Comment by sumedharubasinghe** [comment]
This will help you with respective to building the product.
https://docs.wso2.com/display/IoTS100/Working+with+the+Source+Code

This is a generic document covering all WSO2 Products. So refer to sections
covering WSO2 EMM.
