### ISSUE TITLE
error- Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE]

### ISSUE THREAD

**Issue by MayukhaC** [wso2/product-emm#376]
I am trying to install WSo2EMM Android system service application as i want silently install apps through Wso2 Agent. To get the system root privileges I have used

    android:sharedUserId="android.uid.system"
I have also signed the application using sign-apk.jar and platform.x509.pem, platform.pk8 keys from android source tree. But when I tried to install the signed APK through ADB on both Sony Xperia X peformance and Samsung Galaxy On5. I got the error.

    Failure [INSTALL_FAILED_SHARED_USER_INCOMPATIBLE]
Does the device have to be rooted to sign using the platform keys? I dont want to root my device. is there any alternative or getting the firmware key from the device vendor is the only option I have? If that is the only option how can i get the key from the Vendor?

Thank you

**Comment by kasundananjaya** [comment]
Please note that the system service requires root privileges or the system service needs to be signed by the OS signing certificate. 

If your device is a custom made device or bulk bought, you can request the vendor formally to add this application to the system app pool of the device firmware. Usually vendors provides that service.

Refer http://wso2.com/library/articles/2016/07/article-advanced-handling-of-cope-android-devices-using-wso2-enterprise-mobility-manager/ for more info on this.

**Comment by MayukhaC** [comment]
hi @kasundananjaya 

Thank you for answering. I dont have a customized device or a bulk bought from vendor! Is it still possible to get the device firmware certificate from vendor? Can you enlighten the steps if you can , please? Sorry for the question but i am complete newbie to Android. I have just started 2 weeks ago.

**Comment by kasundananjaya** [comment]
Actually it's not possible that way. Only way you could try this for an individual device would be by rooting it. But we don't recommend it. These features are only available for COPE (corporate owned personally enabled) devices as explained above.

**Comment by kelleyduran** [comment]
We had to have vendor sign the application with a firmware key. There is no other way around it, other than rooting.

**Comment by MayukhaC** [comment]
Thank you for the info @kasundananjaya @kelleyduran
